version: "3.9"

services:
  server-prod:
    build:
      context: ./server
      target: prod
    container_name: node-server-prod
    restart: unless-stopped
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/public:/app/public
    networks:
      - app-network-prod

  haproxy-prod:
    image: haproxy:2.6
    container_name: haproxy-prod
    restart: unless-stopped
    ports:
      - "443:443"   # production HTTPS
      - "8404:8404"
    volumes:
      - ./haproxy.cfg.prod:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /etc/haproxy/certs:/etc/haproxy/certs
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
    depends_on:
      - server-prod
    networks:
      - app-network-prod

networks:
  app-network-prod:
    driver: bridge
