version: "3.9"

services:
  server-staging:
    build: 
      context: ./server
      target: prod
    container_name: node-server-staging
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    env_file: 
      - ./server/.env.staging
    volumes:
      - ./server/public:/app/public
    networks:
      - app-network

  haproxy-staging:
    image: haproxy:2.8-alpine
    container_name: haproxy-staging
    ports:
      - "443:443"
    volumes:
      - ./haproxy.cfg.staging:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /etc/haproxy/certs/pickmymaid-staging.pem:/etc/haproxy/certs/pickmymaid-staging.pem
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
    depends_on:
      - server-staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
